---
#-------------------------------
# General Site Settings
title: "0x10011"
logo: # mylogo.
description: My perspectives on Computer Science.
baseurl: ""
url: "https://khalilli.ai"

#-------------------------------
# Author Settings
author:
  name: Ali Khalilli
  title: I’m Ali Khalilli!
  description: "Machine Learning Engineer with focusing areas: reinforcement learning, deep learning, algorithms & data structures."
  #image: '/images/01.jpg'
  avatar: "/images/avatar.jpeg"
  # /images/01-1.jpg

social:
  - {
      icon: "ion-logo-twitter",
      label: Twitter,
      link: "https://twitter.com/akhalilli",
    }
  - {
      icon: "ion-logo-linkedin",
      label: Linkedin,
      link: "https://linkedin.com/in/alikhalilli/",
    }
  - {
      icon: "ion-logo-github",
      label: Github,
      link: "https://github.com/akhalilli",
    }

# Example of adding a new link to the author section - {icon: "ion-logo-vimeo", label: Vimeo, link: "https://vimeo.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Newsletter (_includes/footer-widgets/widget-subscribe.html)
mailchimp: true # To enable the mailchimp form, use the value 'true'. To disable the form, use the value 'false' or leave the field blank.
mailchimp__title: Get informed # Add your Title
mailchimp__text: Subscribe to my newsletter and I'll send you the emails of latest posts. # Add your description.
mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
mailchimp__button__text: Join # Add your button text

#-------------------------------
# Contact Settings
contact:
  email: me@khalilli.ai # Add your email for contact form
  description: Drop me a message. # Add a description of your form

# NOTE
# Bracia comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

#-------------------------------
# Comment Section (Disqus)
disqus-idisqudentifier: anvodstudio-demo # Add your shortname for Disqus Comment. For example anvodstudio-demo

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: /:title

sass:
  sass_dir: _sass
  style: compressed
